import './globals.css'

export const metadata = {
  title: '小熊AI，您的AI导航伴侣',
  description: 'Generated by 小熊battery',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
