export type ToolDetail = {
  id: number
  slug: string
  name: string
  url: string
  category: string
  categoryName: string
  description: string
  bestFor: string[]
  pricing: string
  difficulty: '入门' | '进阶' | '专业'
  languages: string[]
  pros: string[]
  cons: string[]
  useCases: string[]
  alternatives: string[]
  lastUpdated: string
}

export const toolDetails: ToolDetail[] = [
  {
    id: 1,
    slug: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    category: 'chatbots',
    categoryName: '聊天机器人',
    description: '适合写作、总结、学习、头脑风暴和日常办公的通用 AI 助手。',
    bestFor: ['学生', '上班族', '内容创作者', '小团队'],
    pricing: '提供免费版和付费版，具体价格以官网为准。',
    difficulty: '入门',
    languages: ['中文', '英文', '多语言'],
    pros: ['通用能力强', '适合自然语言交流', '能覆盖写作、分析、代码等多种任务'],
    cons: ['复杂任务需要清晰提示词', '输出内容仍需人工核对', '部分高级能力可能需要付费'],
    useCases: ['整理会议纪要', '改写营销文案', '解释难懂概念', '生成学习计划'],
    alternatives: ['Claude', 'Gemini', '豆包', '通义千问'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 2,
    slug: 'dall-e',
    name: 'DALL-E',
    url: 'https://labs.openai.com',
    category: 'image-generation',
    categoryName: '图像生成',
    description: '通过文字提示生成图片，适合灵感草图、概念图和内容配图。',
    bestFor: ['设计师', '自媒体', '电商运营'],
    pricing: '通常与相关 OpenAI 产品套餐或额度关联，具体以官网为准。',
    difficulty: '入门',
    languages: ['中文', '英文'],
    pros: ['上手门槛低', '适合快速生成创意图', '能配合文本助手优化提示词'],
    cons: ['商业使用前要核对授权', '精确控制画面仍需反复调整'],
    useCases: ['文章封面', '产品概念图', '社媒配图', '广告创意草稿'],
    alternatives: ['Midjourney', 'Stable Diffusion', 'Canva AI'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 3,
    slug: 'midjourney',
    name: 'Midjourney',
    url: 'https://www.midjourney.com',
    category: 'image-generation',
    categoryName: '图像生成',
    description: '偏艺术和视觉表现的 AI 图片生成工具，适合高质感视觉探索。',
    bestFor: ['视觉设计师', '品牌运营', '创意工作者'],
    pricing: '以订阅制为主，价格和套餐以官网为准。',
    difficulty: '进阶',
    languages: ['英文', '中文提示可用但英文更稳定'],
    pros: ['画面质感强', '风格表现丰富', '适合做视觉方向探索'],
    cons: ['精确排版和文字生成不稳定', '需要学习提示词和参数'],
    useCases: ['品牌视觉风格', '海报灵感', '角色概念', '空间氛围图'],
    alternatives: ['DALL-E', 'Stable Diffusion', 'Leonardo AI'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 4,
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    category: 'code-generation',
    categoryName: '代码生成',
    description: '面向开发者的 AI 编程助手，可以辅助补全代码、解释代码和生成测试。',
    bestFor: ['程序员', '技术团队', '编程学习者'],
    pricing: '以订阅制为主，部分人群可能有优惠或免费资格，以官网为准。',
    difficulty: '进阶',
    languages: ['英文', '中文'],
    pros: ['与开发工具集成好', '能提升样板代码编写效率', '适合辅助理解已有代码'],
    cons: ['输出代码必须审查', '不能替代架构和安全判断', '对项目上下文依赖较强'],
    useCases: ['生成单元测试', '解释函数逻辑', '补全重复代码', '编写脚本草稿'],
    alternatives: ['Cursor', 'Codeium', 'Tabnine'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 5,
    slug: 'jasper',
    name: 'Jasper',
    url: 'https://www.jasper.ai',
    category: 'chatbots',
    categoryName: 'AI 写作',
    description: '偏营销和品牌内容生产的 AI 写作平台。',
    bestFor: ['营销团队', '内容运营', '品牌方'],
    pricing: '以付费套餐为主，具体以官网为准。',
    difficulty: '入门',
    languages: ['英文', '多语言'],
    pros: ['营销模板丰富', '适合团队内容流程', '品牌语气管理较友好'],
    cons: ['中文场景需实际测试', '成本可能高于通用聊天工具'],
    useCases: ['广告文案', '博客草稿', '邮件营销', '社媒内容'],
    alternatives: ['ChatGPT', 'Copy.ai', 'Writesonic'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 6,
    slug: 'canva',
    name: 'Canva',
    url: 'https://www.canva.com',
    category: 'image-editing',
    categoryName: '图像编辑',
    description: '集合模板设计、图片编辑和 AI 辅助创作的在线设计平台。',
    bestFor: ['学生', '运营', '电商卖家', '小微企业'],
    pricing: '提供免费版和付费版，具体功能限制以官网为准。',
    difficulty: '入门',
    languages: ['中文', '英文', '多语言'],
    pros: ['模板多', '团队协作方便', '不懂设计也能快速出图'],
    cons: ['高级素材和功能多在付费版', '复杂定制不如专业设计软件'],
    useCases: ['海报', 'PPT', '小红书封面', '商品图'],
    alternatives: ['Figma', 'Adobe Express', '稿定设计'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 7,
    slug: 'deepl',
    name: 'DeepL',
    url: 'https://www.deepl.com',
    category: 'translation',
    categoryName: '翻译',
    description: '适合文档、邮件和跨语言沟通的 AI 翻译工具。',
    bestFor: ['学生', '外贸从业者', '跨国团队'],
    pricing: '提供免费版和付费版，文档翻译和额度以官网为准。',
    difficulty: '入门',
    languages: ['中文', '英文', '日文', '德文', '法文', '多语言'],
    pros: ['译文自然', '适合长文本', '文档翻译流程清晰'],
    cons: ['专业术语仍需人工校对', '部分语言组合效果差异较大'],
    useCases: ['邮件翻译', '论文阅读', '合同初译', '网页内容本地化'],
    alternatives: ['Google Translate', '有道翻译', '腾讯翻译君'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 8,
    slug: 'tableau',
    name: 'Tableau',
    url: 'https://www.tableau.com',
    category: 'data-visualization',
    categoryName: '数据可视化',
    description: '面向企业数据分析和可视化仪表盘的专业平台。',
    bestFor: ['数据分析师', '企业团队', '管理者'],
    pricing: '以商业订阅为主，具体套餐以官网为准。',
    difficulty: '专业',
    languages: ['中文', '英文', '多语言'],
    pros: ['可视化能力成熟', '适合企业报表', '生态和连接器丰富'],
    cons: ['学习成本较高', '个人轻量场景可能过重'],
    useCases: ['经营看板', '销售分析', '用户行为分析', '财务报表'],
    alternatives: ['Power BI', 'Looker Studio', 'FineBI'],
    lastUpdated: '2026-05-22',
  },
  {
    id: 9,
    slug: 'ai-powered-ppt',
    name: 'AI-powered PPT',
    url: 'https://www.aippt.cn/',
    category: 'ppt-generation',
    categoryName: 'PPT 生成',
    description: '通过主题或大纲快速生成演示文稿，适合先出草稿再人工精修。',
    bestFor: ['学生', '职场人', '培训讲师'],
    pricing: '通常提供免费试用或会员能力，具体以官网为准。',
    difficulty: '入门',
    languages: ['中文'],
    pros: ['出稿速度快', '适合搭建汇报结构', '减少排版时间'],
    cons: ['内容深度需要人工补充', '模板风格可能同质化'],
    useCases: ['课程汇报', '商业计划书草稿', '培训课件', '项目复盘'],
    alternatives: ['Canva', 'Gamma', 'Tome'],
    lastUpdated: '2026-05-22',
  },
]

export const toolsBySlug = new Map(toolDetails.map((tool) => [tool.slug, tool]))
